Upgrade to igniter 0.6 to avoid incompatble inflex lib with elixir 1.18
You can observe this

```
$ mix compile
==> inflex
Compiling 6 files (.ex)

== Compilation error in file lib/inflex/pluralize.ex ==
** (ArgumentError) cannot inject attribute @singular into function/macro because cannot escape #Reference<0.3367937475.2023358474.127603>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/inflex/pluralize.ex:179: Inflex.Pluralize.singularize/1
could not compile dependency :inflex, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile inflex --force", update it with "mix deps.update inflex" or clean it with "mix deps.clean inflex"
```

On

```
$ elixir --version
Erlang/OTP 28 [erts-16.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

Elixir 1.18.4 (compiled with Erlang/OTP 28)
```