Upgrade to credo >= 1.7.9 to be compatible with elixir 1.18
You can observe this

```
$ mix compile
==> credo
Compiling 252 files (.ex)

== Compilation error in file lib/credo/check/config_comment_finder.ex ==
** (Regex.CompileError) invalid range in character class at position 16
    (elixir 1.18.4) lib/regex.ex:254: Regex.compile!/2
    lib/credo/check/config_comment_finder.ex:9: (module)
could not compile dependency :credo, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile credo --force", update it with "mix deps.update credo" or clean it with "mix deps.clean credo"
```

On

```
$ elixir --version
Erlang/OTP 28 [erts-16.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

Elixir 1.18.4 (compiled with Erlang/OTP 28)
```